server:
  port: 10000
  address: 0.0.0.0

lavalink:
  server:
    password: "chatgptgay"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    playerUpdateInterval: 5
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 6

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO